### ISSUE TITLE
echod can't dial /ws

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p-circuit-progs#1]
```
$ relay-echod /ip4/127.0.0.1/tcp/9002/ws/ipfs/QmWvZKLrKAzsyiwTSypogt3KBz4SnS1HgupW3vkPTCq8at
2017/07/22 02:52:48 dial attempt failed: <peer.ID TkgM9Z> --> <peer.ID WvZKLr> dial attempt failed: no dialer for /ip4/127.0.0.1/tcp/9002/ws
```

**Comment by vyzo** [comment]
That's because echod and echoc don't bind any ws transport addresses, so they can't find a dailer.

This can be easily fixed by having them bind to a random ws transport address -- `/ip4/0.0.0.0/tcp/0/ws` and `/ip6/::/tcp/0/ws` will do.

**Comment by vyzo** [comment]
Actually the ip6 addr is not needed, as the relay only binds ws to ip4; #2 fixes.
